accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import UserDetailView, RegisterView, UserSearchView, UserUpdateView

app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<int:pk>/edit/', UserUpdateView.as_view(), name='edit_user'),
    path('register/', RegisterView.as_view(), name='register'),
    path('user_search/', UserSearchView.as_view(), name='user_search'),
]

cybergram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import home, PostDetailView, PostUpdateView, PostCreateView, PostDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', home),
    path('home/', home, name='home'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    username = models.CharField(max_length=30, verbose_name='Логин', unique=True)
    email = models.EmailField(unique=True, verbose_name='Адрес электронной почты')
    avatar = models.ImageField(upload_to='avatars', verbose_name='Аватар')
    first_name = models.CharField(max_length=30, verbose_name='Имя', blank=True, null=True)
    last_name = models.CharField(max_length=30, verbose_name='Фамилия', blank=True, null=True)
    user_info = models.TextField(blank=True, null=True, verbose_name='Информация о пользователе')
    phone_number = models.CharField(max_length=20, blank=True, null=True, verbose_name='Номер телефона')
    gender = models.CharField(max_length=20, choices=[('man', 'Муж'), ('woman', 'Жен'), ('other', 'Другой')],
                              blank=True, null=True, verbose_name='Пол')

    def __str__(self):
        return self.username

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=200, blank=True, null=True,)
    description = models.TextField(blank=True, null=True,)
    image = models.ImageField(upload_to='images')
    like_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username', 'email', 'password', 'avatar', 'first_name', 'last_name', 'user_info', 'phone_number', 'gender')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'avatar', 'first_name', 'last_name', 'user_info', 'phone_number', 'gender']


class UserSearchForm(forms.Form):
    search_query = forms.CharField(
        label='Поиск',
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'value': ''})
    )

webapp/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'image']

accounts/views.py
from django.contrib.auth import get_user_model, login
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, ListView, FormView, UpdateView

from accounts.forms import MyUserCreationForm, UserSearchForm, UserProfileForm
from webapp.models import Post


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(author=user)
        return context


class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'user_create.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_page = self.request.GET.get('next')
        if not next_page:
            next_page = self.request.POST.get('next')
        if not next_page:
            next_page = reverse('webapp:home')
        return next_page


class UserUpdateView(UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = 'user_edit.html'

    def get_success_url(self):
        return reverse_lazy('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserSearchView(ListView, FormView):
    model = get_user_model()
    template_name = 'user_search.html'
    context_object_name = 'users'
    form_class = UserSearchForm

    def get_queryset(self):
        search_query = self.request.GET.get('search_query', '')
        if search_query:
            return get_user_model().objects.filter(
                Q(username__icontains=search_query) |
                Q(email__icontains=search_query) |
                Q(first_name__icontains=search_query)
            )
        return get_user_model().objects.none()

webapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.timesince import timesince
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView

from webapp.forms import PostForm
from webapp.models import Post


def home(request):
    posts = Post.objects.all()

    for post in posts:
        post.time_since_post = timesince(post.pub_date, timezone.now())

    return render(request, 'home.html', {'posts': posts})


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post_create.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return redirect('webapp:post_detail', pk=post.pk)


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post_update.html'

    def get_success_url(self):
        return reverse_lazy('webapp:post_detail', kwargs={'pk': self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('webapp:home')

    def get_cancel_url(self):
        return reverse_lazy('webapp:post_detail', kwargs={'pk': self.object.pk})

accounts/templates/login.html
{% extends 'base.html' %}
{% block log_in %}
    <a class="nav-link ms-3" style="font-size: 30px;
                                background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                                -webkit-background-clip: text;
                                -webkit-text-fill-color: transparent;"
                           href="{% url 'accounts:register' %}">
        <i class="bi bi-person-fill-add"></i>
    </a>
{% endblock %}
{% block main %}
    <h1 style="text-align: center">Вход</h1>

    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        <div class="mb-3 ">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" class="form-control mx-auto" id="username" name="username" style="max-width: 300px">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" class="form-control mx-auto" id="password" name="password"  style="max-width: 300px">
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

accounts/templates/partial/user_edit_form.html
{{ form.username.label_tag }}<br>
{{ form.username }}
{{ form.username.errors }}<br>

{{ form.email.label_tag }}<br>
{{ form.email }}
{{ form.email.errors }}<br>

{{ form.first_name.label_tag }}<br>
{{ form.first_name }}
{{ form.first_name.errors }}<br>

{{ form.last_name.label_tag }}<br>
{{ form.last_name }}
{{ form.last_name.errors }}<br>

{{ form.user_info.label_tag }}<br>
{{ form.user_info }}
{{ form.user_info.errors }}<br>

{{ form.phone_number.label_tag }}<br>
{{ form.phone_number }}
{{ form.phone_number.errors }}<br>

{{ form.avatar.label_tag }}<br>
{{ form.avatar }}
{{ form.avatar.errors }}<br>

{{ form.gender.label_tag }}<br>
{{ form.gender }}
{{ form.gender.errors }}<br><br>

accounts/templates/partial/user_form.html
{{ form.username.label_tag }}<br>
{{ form.username }}
{{ form.username.errors }}<br>

{{ form.password.label_tag }}<br>
{{ form.password }}
{{ form.password.errors }}<br>

{{ form.email.label_tag }}<br>
{{ form.email }}
{{ form.email.errors }}<br>

{{ form.first_name.label_tag }}<br>
{{ form.first_name }}
{{ form.first_name.errors }}<br>

{{ form.last_name.label_tag }}<br>
{{ form.last_name }}
{{ form.last_name.errors }}<br>

{{ form.user_info.label_tag }}<br>
{{ form.user_info }}
{{ form.user_info.errors }}<br>

{{ form.phone_number.label_tag }}<br>
{{ form.phone_number }}
{{ form.phone_number.errors }}<br>

{{ form.avatar.label_tag }}<br>
{{ form.avatar }}
{{ form.avatar.errors }}<br>

{{ form.gender.label_tag }}<br>
{{ form.gender }}
{{ form.gender.errors }}<br><br>

accounts/templates/user_create.html
{% extends 'base.html' %}

{% block menu %}
{% endblock %}
{% block search %}
{% endblock %}
{% block log_in %}
{% endblock %}

{% block main %}
    <h2>Регистрация:</h2>
    <form enctype="multipart/form-data" method="post" action="{% url 'accounts:register' %}">
        {% csrf_token %}
        {% include 'partial/user_form.html' %}
        <button class="btn btn-primary mb-5" type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block log_in %}
    <form method="post" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <button class="nav-link" style="font-size: 30px;
            background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;" type="submit">
                <i class="bi bi-person-fill-dash"></i>
        </button>
    </form>
{% endblock %}
{% block main %}
    <div class="user_profile" style="display: flex; margin-top: 50px; margin-bottom: 60px">
        <div class="user_image">
            <img style="border-radius: 50%; width: 250px; height: 250px" src="{{ user.avatar.url }}" alt="Avatar">
        </div>
        <div class="user_info" style="margin-left: 100px;">
            <div class="user_title" style="display: flex; margin-bottom: 25px">
                <span style="font-size: 30px;">{{ user.username }}</span>
                <div class="user_create">
                    <a class="btn btn-outline-secondary ms-4" href="{% url 'accounts:edit_user' pk=user.pk %}">Редактировать профиль</a>
                </div>
            </div>
            <div class="counts" style="margin-bottom: 40px">
                <span>*публикаций</span>
                <span style="margin-left: 30px">*подписчиков</span>
                <span style="margin-left: 30px">*Подписки:</span>
            </div>
            <div class="info">
                <span><b>{{ user.first_name }} {{ user.last_name }}</b></span><br>
                <span>{{ user.user_info }}</span>
            </div>
        </div>
    </div>
    <div style="display: flex">
        {% for post in posts %}
            <div style="border: 2px solid white">
                <a href="{% url 'webapp:post_detail' pk=post.pk %}">
                    <img style="width: 240px; height: 240px" src="{{ post.image.url }}" alt="Image">
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/user_edit.html
{% extends 'base.html' %}

{% block menu %}
{% endblock %}
{% block search %}
{% endblock %}
{% block log_in %}
{% endblock %}

{% block main %}
    <h2>Редактирование пользователя:</h2>
    <form enctype="multipart/form-data" method="post" action="{% url 'accounts:edit_user' pk=user.pk %}">
        {% csrf_token %}
        {% include 'partial/user_edit_form.html' %}
        <button class="btn btn-primary mb-5" type="submit">Сохранить</button>
    </form>
{% endblock %}

accounts/templates/user_search.html
{% extends 'base.html' %}
{% block search %}
    <form method="get">
        <input class="" type="text" placeholder="Поиск" name="search_query" value="{{ request.GET.search_query }}">
        <button class="btn btn-primary mb-1" type="submit">Найти</button>
    </form>
{% endblock %}
{% block main %}
    <h3>Поиск пользователей</h3>
    {% if users %}
        <h3>Результаты поиска:</h3>
        <ul>
            {% for user in users %}
                <li>
                    <a style="text-decoration: none; color: black"
                       href="{% url 'accounts:user_detail' pk=user.pk %}"><b>{{ user.username }}</b></a>
                </li>
            {% endfor %}
        </ul>

    {% endif %}
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet">
    {% block title %}<title>Cybergram</title>{% endblock %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary p-3 mb-4">
        <div class="container">
            <a class="navbar-brand" style="font-family: 'Lemon', serif; font-size: 25px;
                background: #FFCB1F;
                background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;" href="{% url 'webapp:home' %}">
                <span>Cybergram</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <div class="navbar-nav">
                    {% block menu %}
                        <a class="nav-link" href="{% url 'webapp:post_create' %}">Add Post</a>
                    {% endblock %}
                </div>
                {% block search %}
                    <a class="nav-link" href="{% url 'accounts:user_search' %}">Search</a>
                {% endblock %}
                <div class="log_in" style="display: flex">
                    {% block log_in %}
                        {% if not request.user.is_authenticated %}
                            <a class="nav-link" style="font-size: 30px;
                                    background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                                    -webkit-background-clip: text;
                                    -webkit-text-fill-color: transparent;"
                               href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">
                                <i class="bi bi-person-fill-up"></i>
                            </a>
                            <a class="nav-link ms-3" style="font-size: 30px;
                                    background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                                    -webkit-background-clip: text;
                                    -webkit-text-fill-color: transparent;"
                               href="{% url 'accounts:register' %}?next={{ request.get_full_path }}">
                                <i class="bi bi-person-fill-add"></i>
                            </a>
                        {% else %}
                            <a class="nav-link" style="font-size: 30px;
                                    background: linear-gradient(to right, #FFCB1F 42%, #FF1A16 81%);
                                    -webkit-background-clip: text;
                                    -webkit-text-fill-color: transparent;"
                               href="{% url 'accounts:user_detail' pk=user.pk %}">
                                <i class="bi bi-person-fill-check"></i>
                            </a>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}
<div class="container">
    {% block main %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>
</html>

webapp/templates/home.html
{% extends 'base.html' %}
{% block menu %}
{% endblock %}
{% block main %}
    {% for post in posts %}
        <div class="user_link mb-2">

            <a style="color: black; text-decoration: none;"
                      href="{% url 'accounts:user_detail' pk=post.author.pk %}">
                <img style="border-radius: 50%; width: 40px; height: 40px" src="{{ post.author.avatar.url }}" alt="Image">
                <b>{{ post.author.username }}</b></a>
        </div>

        <img class="mb-2" style="width: 800px" src="{{ post.image.url }}" alt="{{ post.title }}">
        <div class="mb-4">
            <div style="font-size: 30px;">
                <i class="bi bi-heart"></i>
                <i class="bi bi-chat ms-3"></i>
            </div>
            <span><b>{{ post.like_count }} отметок "Нравится"</b></span><br>
            <span><a style="color: black; text-decoration: none;"
                  href="{% url 'accounts:user_detail' pk=post.author.pk %}"><b>{{ post.author.username }}</b></a> {{ post.title }}
            </span><br>
            <span>{{ post.description }}</span><br>
            <span style="color: #8f8f8f">Все комментарии ({{ post.comment_count }})</span><br>
            <span style="color: #8f8f8f">{{ post.time_since_post }} ago</span>
        </div>
    {% endfor %}
{% endblock %}

webapp/templates/partial/post_form.html
{{ form.image.label_tag }}<br>
{{ form.image }}
{{ form.image.errors }}<br>

{{ form.title.label_tag }}<br>
{{ form.title }}
{{ form.title.errors }}<br>

{{ form.description.label_tag }}<br>
{{ form.description }}
{{ form.description.errors }}<br><br>

webapp/templates/post_create.html
{% extends 'base.html' %}

{% block menu %}
{% endblock %}
{% block search %}
{% endblock %}
{% block log_in %}
{% endblock %}

{% block main %}
    <h2>Создание поста:</h2>
    <form enctype="multipart/form-data" method="post" action="{% url 'webapp:post_create' %}">
        {% csrf_token %}
        {% include 'partial/post_form.html' %}
        <button class="btn btn-primary mb-5" type="submit">Создать</button>
    </form>
{% endblock %}

webapp/templates/post_delete.html
{% extends 'base.html' %}
{% block main %}
    <h1>Вы точно хотите удалить пост "{{ post.title }}"?</h1>
    <form style="display: inline;" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Удалить</button>
    </form>
    <a class="btn btn-primary ms-3" href="{% url 'webapp:post_detail' pk=post.pk %}">Отмена</a>
{% endblock %}

webapp/templates/post_detail.html
{% extends 'base.html' %}
{% block menu %}
{% endblock %}
{% block main %}
    <div class="user_link mb-2">
            <a style="color: black; text-decoration: none;"
                      href="{% url 'accounts:user_detail' pk=post.author.pk %}">
                <img style="border-radius: 50%; width: 40px; height: 40px" src="{{ post.author.avatar.url }}" alt="Image">
                <b>{{ post.author.username }}</b></a>
    </div>
    <img class="mb-2" style="width: 800px" src="{{ post.image.url }}" alt="{{ post.title }}">
    <div class="mb-4">
        <div style="font-size: 30px;">
            <i class="bi bi-heart"></i>
            <i class="bi bi-chat ms-3"></i>
        </div>
        <span><b>{{ post.like_count }} отметок "Нравится"</b></span><br>
        <span><a style="color: black; text-decoration: none;"
                 href="{% url 'accounts:user_detail' pk=post.author.pk %}"><b>{{ post.author.username }}</b></a> {{ post.title }}
            </span><br>
        <span>{{ post.description }}</span><br>
        <span style="color: #8f8f8f">Все комментарии ({{ post.comment_count }})</span><br>
    </div>
    <a class="btn btn-primary" href="{% url 'webapp:post_edit' pk=post.pk %}">Изменить</a>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:post_delete' pk=post.pk %}">Удалить</a>
{% endblock %}

webapp/templates/post_update.html
{% extends 'base.html' %}

{% block menu %}
{% endblock %}
{% block search %}
{% endblock %}
{% block log_in %}
{% endblock %}

{% block main %}
    <h2>Изменения поста:</h2>
    <form style="display: inline" enctype="multipart/form-data" method="post" action="{% url 'webapp:post_edit' pk=post.pk %}">
        {% csrf_token %}
        {% include 'partial/post_form.html' %}
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
    <a class="btn btn-danger ms-3" href="{% url 'webapp:post_detail' pk=post.pk %}">Отмена</a>
{% endblock %}